### ISSUE TITLE
dockage.dev unreachable

### ISSUE THREAD

**Issue by petrsimunek** [dockage/mailcatcher#6]
Hello, I was looking for documentation, but the site dockage.dev is not reachable for me...

**Comment by Darkskynet** [comment]
24 April, 2023 dockage.dev is still down.

**Comment by x-vlad-x** [comment]
December 20, still down

**Comment by EMaksy** [comment]
29.01.2024 still down :)

**Comment by mortymacs** [comment]
Hello everyone!

Sorry for the delay.
Our website will be live later this month, and we're also jazzing up the containers. Can't wait to share it all with you! 🚀

**Comment by ValentinAUCLERC** [comment]
Still down... Is this project dead ?

**Comment by mortymacs** [comment]
Hello!

I'm really sorry about that! I made a mistake and accidentally removed my comment. My apologies for any confusion that caused.
Finally, today we could make the website ready and now it's available https://dockage.dev
